# Generated by Django 2.0.7 on 2018-07-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=10)),
                ('Manual_id', models.IntegerField()),
            ],
        ),
    ]
